<a href="https://colab.research.google.com/github/lmcanavals/acomplex/blob/main/1103_knapsack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def knapsack(i, j, W, V, C):
    if i == 0 or j == 0:
        C[i, j] = 0
    else:
        if C[i - 1, j] == -1:
            knapsack(i - 1, j, W, V, C)
        if W[i] <= j and C[i - 1, j - W[i]] == -1:
            knapsack(i - 1, j - W[i], W, V, C)
        if W[i] > j:
            C[i, j] = C[i - 1, j]
        else:
            C[i, j] = max(V[i] + C[i - 1, j - W[i]], C[i - 1, j])

In [ ]:
N = 4
M = 5
W = [0, 2, 3, 4, 5]
V = [0, 3, 4, 5, 6]
C = np.zeros((N + 1, M + 1)) - 1
knapsack(N, M, W, V, C)
print(C)

[[ 0.  0.  0.  0. -1.  0.]
 [-1.  0.  3. -1. -1.  3.]
 [-1.  0. -1. -1. -1.  7.]
 [ 0. -1. -1. -1. -1.  7.]
 [-1. -1. -1. -1. -1.  7.]]
