<a href="https://colab.research.google.com/github/lmcanavals/acomplex/blob/main/1599_forkfulkerson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import math
import numpy as np

In [9]:
def dfs(G, s, t):
    n = len(G)
    visited = [False]*n
    path = [-1]*n
    stack = [s]
    while stack:
        u = stack.pop()
        if u == t:
            break
        if not visited[u]:
            visited[u] = True
            for v in reversed(range(n)):
                if G[u][v] > 0 and not visited[v]:
                    stack.append(v)
                    path[v] = u

    p = [t]
    bottleneck = math.inf
    while path[t] != -1:
        if G[path[t]][t] < bottleneck:
            bottleneck = G[path[t]][t]
        t = path[t]
        p.append(t)

    return p, bottleneck

In [3]:
%%file graph.x
0 6 4 1 0 0 0
0 0 0 0 4 0 0
0 0 0 3 1 3 0
0 0 0 0 0 4 0
0 0 0 0 0 0 4
0 0 0 0 0 0 9
0 0 0 0 0 0 0

Writing graph.x


In [5]:
G = np.loadtxt("graph.x", dtype=int, delimiter=" ")
G

array([[0, 6, 4, 1, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 3, 1, 3, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0]])

In [6]:
labels = ['I', 'A', 'B', 'C', 'D', 'E', 'F']

In [19]:
path, bn = dfs(G, 0, 6)
[labels[x] for x in reversed(path)], bn

(['I', 'A', 'D', 'F'], 4)

In [22]:
#import pdb

def fordFulkerson(G, s, t):
    Gr = np.zeros_like(G)
    Gf = np.zeros_like(G)

    Gr = G.copy()
    while True:
        #pdb.set_trace()
        apath, bn = dfs(Gr, s, t)
        if bn == math.inf:
            break

        v = apath[0]
        for u in apath[1:]:
            Gr[u, v] -= bn
            Gr[v, u] += bn
            Gf[u, v] += bn
            v = u

    return Gf

In [23]:
fordFulkerson(G, 0, 6)

array([[0, 4, 4, 1, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 3, 0, 2, 0],
       [0, 0, 1, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0]])

In [26]:
%%file 1.2
0 9 12 0 0 0 0
0 0 6 9 4 3 0
0 0 0 2 6 3 0
0 0 0 0 2 0 7
0 0 0 0 0 2 8
0 0 0 0 0 0 5
0 0 0 0 0 0 0

Overwriting 1.2


In [27]:
G = np.loadtxt("1.2", dtype=int, delimiter=" ")
G

array([[ 0,  9, 12,  0,  0,  0,  0],
       [ 0,  0,  6,  9,  4,  3,  0],
       [ 0,  0,  0,  2,  6,  3,  0],
       [ 0,  0,  0,  0,  2,  0,  7],
       [ 0,  0,  0,  0,  0,  2,  8],
       [ 0,  0,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [28]:
fordFulkerson(G, 0, 6)

array([[ 0,  9, 11,  0,  0,  0,  0],
       [ 0,  0,  6,  9,  3,  1,  0],
       [ 0,  6,  0,  4,  7,  3,  0],
       [ 0,  2,  2,  0,  4,  0,  7],
       [ 0,  1,  1,  2,  0,  2,  8],
       [ 0,  1,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0]])